[workspace]
resolver = "2"
members = [
    "crates/vv-core",
    "crates/vv-media",
    "crates/vv-render",
    "crates/vv-audio",
    "crates/vv-app",
]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = "thin"
codegen-units = 1
