//! End-to-end exports of timelines built through the app (import and
//! append), not by hand.

use super::*;
use std::sync::atomic::AtomicBool;
use vv_session::export::{ExportProgress, ExportSettings, export_timeline};

/// End-to-end: builds a real timeline (via `VenturiApp`, not
/// `Clip`/`Track` by hand) with a real video+audio file generated by
/// the ffmpeg CLI (same pattern as the tests in `main.rs`), exports, and
/// checks the result by reading it back with `vv_media` — the only way to
/// verify the export in this environment, without a display.
#[test]
fn export_timeline_produces_a_playable_file_matching_the_timeline() {
    let dir = std::env::temp_dir().join("vv-app-export-test");
    std::fs::create_dir_all(&dir).unwrap();
    let source_path = dir.join("source.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=64x48:rate=25:duration=1",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=1",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
        ],
        &source_path,
    );

    let mut app = crate::VenturiApp::default();
    app.import_media(source_path);
    let timeline_id = app
        .timeline_id
        .expect("import should have created the timeline");
    let media_id = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .expect("imported media expected in the pool");
    app.add_media_to_timeline(media_id);

    let output_path = dir.join("out.mp4");
    let progress = Mutex::new(ExportProgress::default());
    let cancel = AtomicBool::new(false);
    let total = app.session.project.timelines[timeline_id].total_frames();
    let settings = ExportSettings::new(output_path.clone());
    export_timeline(
        &app.session.project,
        timeline_id,
        &settings,
        0..total,
        &progress,
        &cancel,
    )
    .expect("export failed");

    let p = progress.lock().unwrap();
    assert!(p.done);
    assert!(p.fps().is_some());
    for stage in [p.decode, p.compose, p.encode] {
        assert_eq!(stage.frames, total);
        assert!(stage.fps().is_some());
    }
    assert_eq!(p.decoders, [None]);
    assert!(p.compositor.is_some());
    assert_eq!(p.encoder, Some(vv_media::VideoCodec::X264));
    assert_eq!(p.output_path, output_path);
    assert!(p.startup.is_some() && p.finalize.is_some());
    assert!(
        p.busy_share(&p.encode)
            .is_some_and(|share| share > 0.0 && share <= 1.0)
    );
    drop(p);

    let meta = vv_media::probe(&output_path).unwrap();
    assert_eq!(meta.width, 64);
    assert_eq!(meta.height, 48);
    assert!(meta.has_audio);

    let mut decoder = vv_media::Decoder::open(&output_path).unwrap();
    let mut count = 0;
    while decoder.next_frame().unwrap().is_some() {
        count += 1;
    }
    // ~25fps for 1s, the same tolerance already used for the B-frame
    // encoder reordering seen in the `vv_media::encode` tests.
    assert!((24..=25).contains(&count), "count={count}");

    let audio = vv_media::decode_audio_track(&output_path, 0)
        .unwrap()
        .expect("audio expected in the export");
    let peak = audio.samples.iter().cloned().fold(0.0_f32, f32::max);
    assert!(peak > 0.1, "peak={peak}, expected a non-silent signal");
}

/// End-to-end regression for exporting an image (see
/// `ActiveClipDecoder::open_for`): the default clip (5s = 125
/// frames at 25fps) covers well past the single real frame
/// an image has — before the dedicated support the export would
/// have errored out (or stopped) as soon as it went past the first
/// requested position.
#[test]
fn export_timeline_covers_a_stretched_image_clip_past_its_only_real_frame() {
    let dir = std::env::temp_dir().join("vv-app-export-image-test");
    std::fs::create_dir_all(&dir).unwrap();
    let source_path = dir.join("still.png");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "color=c=yellow:size=64x48:rate=1:duration=1",
            "-frames:v",
            "1",
            "-update",
            "1",
        ],
        &source_path,
    );

    let mut app = crate::VenturiApp::default();
    app.import_media(source_path);
    let timeline_id = app
        .timeline_id
        .expect("import should have created the timeline");
    let media_id = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .expect("imported media expected in the pool");
    assert!(app.session.project.media_pool[media_id].meta.is_image());
    app.add_media_to_timeline(media_id);

    let output_path = dir.join("out.mp4");
    let progress = Mutex::new(ExportProgress::default());
    let cancel = AtomicBool::new(false);
    let total = app.session.project.timelines[timeline_id].total_frames();
    assert_eq!(total, 5 * 25, "5 s by default at 25 fps");
    let settings = ExportSettings::new(output_path.clone());
    export_timeline(
        &app.session.project,
        timeline_id,
        &settings,
        0..total,
        &progress,
        &cancel,
    )
    .expect("export failed");

    assert!(progress.lock().unwrap().done);

    let mut decoder = vv_media::Decoder::open(&output_path).unwrap();
    let mut count = 0;
    while let Some((_, frame)) = decoder.next_frame().unwrap() {
        // Yellow over the whole frame, for the whole export: if
        // the image "ended" halfway, black would appear here (or an
        // error would already have interrupted the export above).
        assert!(
            frame.y[0] > 150,
            "expected the image frame still, not black"
        );
        count += 1;
    }
    assert!((total - 1..=total).contains(&count), "count={count}");
}

/// The bug case, end-to-end: a clip at 23.976 fps appended onto a
/// timeline at 25 (created from the first media, at 25). Conformed, the
/// second clip occupies its real time on the timeline, so the exported
/// file lasts as long as the two clips together and the audio of the second
/// reaches the very end instead of finishing before the video.
#[test]
fn export_conforms_a_clip_whose_fps_differs_from_the_timeline() {
    let dir = std::env::temp_dir().join("vv-app-export-conform-test");
    std::fs::create_dir_all(&dir).unwrap();

    let mute_25 = dir.join("mute25.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=64x48:rate=25:duration=1",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=sample_rate=48000:channel_layout=stereo",
            "-t",
            "1",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
        ],
        &mute_25,
    );

    // 24000/1001 = 23.976 fps: 48 source frames for 2 real s.
    let sine_23976 = dir.join("sine23976.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=64x48:rate=24000/1001:duration=2",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
        ],
        &sine_23976,
    );

    let mut app = crate::VenturiApp::default();
    app.import_media(mute_25);
    let timeline_id = app
        .timeline_id
        .expect("import should have created the timeline");
    assert_eq!(
        app.session.project.timelines[timeline_id].fps,
        vv_core::Rational::new(25, 1)
    );
    let first = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .unwrap();
    app.add_media_to_timeline(first);

    app.import_media(sine_23976);
    let second = app
        .session
        .project
        .media_pool
        .iter()
        .filter(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .find(|id| *id != first)
        .expect("second media expected in the pool");
    let second_start = app.session.project.timelines[timeline_id].total_frames();
    app.add_media_to_timeline(second);

    let conformed = app.session.project.timelines[timeline_id]
        .tracks
        .iter()
        .flat_map(|t| t.clips.iter())
        .find(|c| c.timeline_start == second_start)
        .expect("conformed clip expected");
    assert_ne!(conformed.rate(), vv_core::Rational::one());
    let total = app.session.project.timelines[timeline_id].total_frames();
    // 1 s at 25 fps + 2 s conformed to 25 fps, within one frame of
    // rounding on the duration reported by ffmpeg.
    assert!((74..=76).contains(&total), "total={total}");

    let output_path = dir.join("out.mp4");
    let progress = Mutex::new(ExportProgress::default());
    export_timeline(
        &app.session.project,
        timeline_id,
        &ExportSettings::new(output_path.clone()),
        0..total,
        &progress,
        &AtomicBool::new(false),
    )
    .expect("export failed");

    let mut decoder = vv_media::Decoder::open(&output_path).unwrap();
    let mut count = 0;
    while decoder.next_frame().unwrap().is_some() {
        count += 1;
    }
    assert!((total - 1..=total).contains(&count), "count={count}");

    let audio = vv_media::decode_audio_track(&output_path, 0)
        .unwrap()
        .expect("audio expected in the export");
    let frames = audio.samples.len() / audio.channels as usize;
    let secs = frames as f64 / audio.sample_rate as f64;
    let expected_secs = total as f64 / 25.0;
    assert!(
        (secs - expected_secs).abs() < 0.1,
        "audio {secs}s versus {expected_secs}s of video"
    );

    // The audio of the second clip covers its stretch to the end:
    // if the video were mapped 1:1 onto the source frames, the timeline
    // would end earlier and the tail of the sine would be cut off.
    let peak_in = |from_secs: f64, to_secs: f64| {
        let ch = audio.channels as usize;
        let from = (from_secs * audio.sample_rate as f64) as usize * ch;
        let to = ((to_secs * audio.sample_rate as f64) as usize * ch).min(audio.samples.len());
        audio.samples[from.min(to)..to]
            .iter()
            .fold(0.0_f32, |m, s| m.max(s.abs()))
    };
    assert!(peak_in(0.1, 0.9) < 0.05, "the first clip is muted");
    assert!(peak_in(1.1, 1.9) > 0.1, "the second clip plays");
    assert!(
        peak_in(expected_secs - 0.2, expected_secs) > 0.1,
        "the sine must reach the end of the timeline"
    );
}

#[test]
fn export_timeline_scales_the_output_and_can_drop_the_audio() {
    let dir = std::env::temp_dir().join("vv-app-export-scale-test");
    std::fs::create_dir_all(&dir).unwrap();
    let source_path = dir.join("source.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=64x48:rate=25:duration=1",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000:duration=1",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
        ],
        &source_path,
    );

    let mut app = crate::VenturiApp::default();
    app.import_media(source_path);
    let media_id = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .unwrap();
    app.add_media_to_timeline(media_id);
    let timeline_id = app.timeline_id.unwrap();
    let total = app.session.project.timelines[timeline_id].total_frames();

    let mut settings = ExportSettings::new(dir.join("out.mp4"));
    settings.scale_percent = 50;
    settings.audio = None;
    export_timeline(
        &app.session.project,
        timeline_id,
        &settings,
        0..total,
        &Mutex::new(ExportProgress::default()),
        &AtomicBool::new(false),
    )
    .expect("export failed");

    let meta = vv_media::probe(&settings.output_path).unwrap();
    assert_eq!((meta.width, meta.height), (32, 24));
    assert!(!meta.has_audio);
}

#[test]
fn export_timeline_writes_only_the_in_out_range() {
    let dir = std::env::temp_dir().join("vv-app-export-range-test");
    std::fs::create_dir_all(&dir).unwrap();
    let source_path = dir.join("source.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=64x48:rate=25:duration=1",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
        ],
        &source_path,
    );

    let mut app = crate::VenturiApp::default();
    app.import_media(source_path);
    let media_id = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .unwrap();
    app.add_media_to_timeline(media_id);
    let timeline_id = app.timeline_id.unwrap();

    let output_path = dir.join("out.mp4");
    let progress = Mutex::new(ExportProgress::default());
    export_timeline(
        &app.session.project,
        timeline_id,
        &ExportSettings::new(output_path.clone()),
        5..15,
        &progress,
        &AtomicBool::new(false),
    )
    .expect("export failed");
    assert_eq!(progress.lock().unwrap().total_frames, 10);

    let mut decoder = vv_media::Decoder::open(&output_path).unwrap();
    let mut count = 0;
    while decoder.next_frame().unwrap().is_some() {
        count += 1;
    }
    assert!((9..=10).contains(&count), "count={count}");
}

#[test]
fn run_export_goes_through_the_session_and_keeps_the_outcome_readable() {
    let dir = std::env::temp_dir().join("vv-app-run-export");
    std::fs::create_dir_all(&dir).unwrap();
    let output_path = dir.join("out.mp4");
    let _ = std::fs::remove_file(&output_path);

    let mut app = crate::VenturiApp::default();
    let timeline_id = app.ensure_timeline();
    vv_core::edit::insert_generator(
        &mut app.session.project,
        &mut app.session.history,
        timeline_id,
        vv_core::edit::Generator::SolidColor,
        0,
        0,
        None,
    );
    let mut settings = ExportSettings::new(output_path.clone());
    settings.scale_percent = 10;
    app.run_export(timeline_id, settings, 0..10);

    let ctx = egui::Context::default();
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(60);
    while app.session.has_running_jobs() {
        assert!(
            std::time::Instant::now() < deadline,
            "export never finished"
        );
        app.poll_session(&ctx);
        std::thread::sleep(std::time::Duration::from_millis(10));
    }
    app.poll_session(&ctx);

    let progress = app
        .export
        .as_ref()
        .expect("the window stays open")
        .progress
        .clone();
    let progress = progress.lock().unwrap();
    assert!(progress.done);
    assert!(progress.error.is_none(), "{:?}", progress.error);
    // Same one-frame encoder tolerance as the other export tests.
    let frames = vv_media::probe(&output_path).unwrap().duration_frames;
    assert!((9..=10).contains(&frames), "frames={frames}");
}

/// Without a usable GPU decoder (CI) it falls back to the CPU; with one, the
/// hwaccels decode H.264 bit-exactly, so the export does not change.
#[test]
fn export_decoding_on_the_gpu_writes_the_same_frames_as_on_the_cpu() {
    let dir = std::env::temp_dir().join("vv-app-export-hw-test");
    std::fs::create_dir_all(&dir).unwrap();
    let source_path = dir.join("source.mp4");
    vv_media::test_support::ffmpeg(
        &[
            "-f",
            "lavfi",
            "-i",
            "testsrc=size=320x240:rate=25:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
        ],
        &source_path,
    );
    let mut app = crate::VenturiApp::default();
    app.import_media(source_path);
    let timeline_id = app.timeline_id.unwrap();
    let media_id = app
        .session
        .project
        .media_pool
        .iter()
        .find(|(_, item)| item.compound.is_none())
        .map(|(id, _)| id)
        .unwrap();
    app.add_media_to_timeline(media_id);
    let total = app.session.project.timelines[timeline_id].total_frames();

    let export = |name: &str, hw_decode: Vec<vv_media::HwDevice>| {
        let mut settings = ExportSettings::new(dir.join(name));
        settings.audio = None;
        settings.hw_decode = hw_decode;
        export_timeline(
            &app.session.project,
            timeline_id,
            &settings,
            0..total,
            &Mutex::new(ExportProgress::default()),
            &AtomicBool::new(false),
        )
        .unwrap();
        let mut decoder = vv_media::Decoder::open(&settings.output_path).unwrap();
        let mut frames = Vec::new();
        while let Some((_, frame)) = decoder.next_frame().unwrap() {
            frames.push(frame.y.clone());
        }
        frames
    };
    let cpu = export("cpu.mp4", Vec::new());
    let gpu = export(
        "gpu.mp4",
        vec![
            vv_media::HwDevice::VideoToolbox,
            vv_media::HwDevice::Cuda,
            vv_media::HwDevice::Vulkan(None),
        ],
    );
    // Same tolerance for the encoder's B-frame reordering as above.
    assert!(cpu.len() as FrameIdx >= total - 1, "{} frames", cpu.len());
    assert!(cpu == gpu, "the GPU export differs from the CPU one");
}
