//! Audio peaks for drawing the waveform on the timeline. Global on-disk
//! cache keyed by `content_hash` + stream, like the proxies; generated by
//! `vv-app::waveform_worker`, never on the UI thread.
//!
//! The bins cover the duration of the *audio track*, not of the container:
//! the duration is saved in the file and the drawing uses the same base,
//! otherwise the waveform slides relative to the sound when audio and video
//! have different durations.

use ffmpeg::media::Type;
use ffmpeg_next as ffmpeg;
use std::ops::ControlFlow;
use std::path::{Path, PathBuf};

/// Number of peaks per second of audio: enough to make the waveform
/// readable even at medium/high zoom, with a contained cache file
/// (~4 bytes/peak → 100 peaks/s ≈ 400 B/s ≈ 1.4 MB for an hour).
const PEAKS_PER_SECOND: f64 = 100.0;
/// Floor and ceiling on the number of peaks: a very short clip does not deserve
/// more than a hundred bins (they would all be equal), a very long file must
/// not inflate the cache past a reasonable limit.
const MIN_PEAKS: usize = 100;
const MAX_PEAKS: usize = 200_000;

/// Recommended number of peaks for a media of `duration_secs` seconds:
/// proportional to the duration, clamped to `[MIN_PEAKS, MAX_PEAKS]`.
pub fn recommended_num_peaks(duration_secs: f64) -> usize {
    let raw = (duration_secs * PEAKS_PER_SECOND).round() as usize;
    raw.clamp(MIN_PEAKS, MAX_PEAKS)
}

pub fn waveforms_dir() -> PathBuf {
    crate::cache_dir("waveforms")
}

/// Path of the peaks file of a stream, whether it exists or not.
pub fn waveform_path_for(content_hash: u64, stream_index: usize) -> PathBuf {
    waveforms_dir().join(format!("{content_hash:016x}_{stream_index}.peaks"))
}

/// Does the file exist *in the current format*? A file from an earlier
/// `PEAKS_VERSION` would be discarded by `load_waveform`, but with a plain
/// `is_file()` the worker would never regenerate it. Reads the header only.
pub fn waveform_exists(content_hash: u64, stream_index: usize) -> bool {
    use std::io::Read;
    let Ok(mut f) = std::fs::File::open(waveform_path_for(content_hash, stream_index)) else {
        return false;
    };
    let mut header = [0u8; 8];
    if f.read_exact(&mut header).is_err() {
        return false;
    }
    &header[..4] == PEAKS_MAGIC && u32::from_le_bytes(header[4..8].try_into().unwrap()) == PEAKS_VERSION
}

/// The peaks of a waveform and the duration of the audio track they cover
/// (in seconds): the duration is needed by the drawing to map the clip bins
/// onto the same time base as the peaks (see the module docs).
pub struct Waveform {
    pub peaks: Vec<f32>,
    /// Duration of the audio track (in seconds) covered by `peaks`.
    pub audio_duration_secs: f64,
}

/// Peaks of the `stream_indices` streams in a single read of the file,
/// `num_peaks` bins each in [0,1], written atomically (tmp +
/// `rename`). `None` for a non-existent stream.
pub fn generate_waveforms(
    source_path: &Path,
    content_hash: u64,
    stream_indices: &[usize],
    num_peaks: usize,
) -> Result<Vec<Option<Waveform>>, crate::MediaError> {
    crate::probe::ensure_init();
    let mut bins: Vec<Option<PeakBins>> = audio_stream_timing(source_path, stream_indices)?
        .into_iter()
        .map(|timing| timing.map(|(secs, rate)| PeakBins::new(secs, rate, num_peaks)))
        .collect();
    crate::audio::decode_audio_streams_streaming(
        source_path,
        stream_indices,
        None,
        |slot, channels, chunk| {
            if let Some(bins) = &mut bins[slot] {
                bins.push(chunk, channels as usize);
            }
            ControlFlow::Continue(())
        },
    )?;

    let dir = waveforms_dir();
    std::fs::create_dir_all(&dir)?;
    let mut out = Vec::with_capacity(bins.len());
    for (&stream_index, bins) in stream_indices.iter().zip(bins) {
        let Some(bins) = bins else {
            out.push(None);
            continue;
        };
        let waveform = bins.finish();
        let tmp_path = dir.join(format!(
            "{content_hash:016x}_{stream_index}.tmp-{}.peaks",
            std::process::id()
        ));
        write_peaks_file(&tmp_path, &waveform.peaks, waveform.audio_duration_secs)?;
        std::fs::rename(&tmp_path, waveform_path_for(content_hash, stream_index))?;
        out.push(Some(waveform));
    }
    Ok(out)
}

#[cfg(test)]
fn generate_waveform(
    source_path: &Path,
    content_hash: u64,
    stream_index: usize,
    num_peaks: usize,
) -> Result<Option<Waveform>, crate::MediaError> {
    Ok(generate_waveforms(source_path, content_hash, &[stream_index], num_peaks)?
        .pop()
        .flatten())
}

/// `(duration in seconds, sample rate)` of each requested audio stream.
/// The duration is the track's (in its own time_base); if the format does
/// not report it, the container's.
fn audio_stream_timing(
    path: &Path,
    stream_indices: &[usize],
) -> Result<Vec<Option<(f64, u32)>>, crate::MediaError> {
    let ictx = ffmpeg::format::input(path)?;
    let container_secs = ictx.duration() as f64 / f64::from(ffmpeg::ffi::AV_TIME_BASE);
    let streams: Vec<_> = ictx
        .streams()
        .filter(|s| s.parameters().medium() == Type::Audio)
        .collect();
    stream_indices
        .iter()
        .map(|&i| {
            let Some(stream) = streams.get(i) else {
                return Ok(None);
            };
            let rate = ffmpeg::codec::context::Context::from_parameters(stream.parameters())?
                .decoder()
                .audio()?
                .rate();
            let tb = stream.time_base();
            let secs = stream.duration() as f64 * tb.0 as f64 / tb.1 as f64;
            Ok(Some((if secs > 0.0 { secs } else { container_secs }, rate)))
        })
        .collect()
}

/// Peaks under construction for one stream.
struct PeakBins {
    peaks: Vec<f32>,
    /// Fractional: truncating it would accumulate lag along the file.
    samples_per_bin: f64,
    /// Audio frames (one sample per channel) seen so far.
    frames_seen: usize,
    audio_duration_secs: f64,
}

impl PeakBins {
    fn new(audio_duration_secs: f64, sample_rate: u32, num_peaks: usize) -> Self {
        let num_peaks = num_peaks.max(1);
        Self {
            peaks: vec![0.0; num_peaks],
            samples_per_bin: (audio_duration_secs * sample_rate as f64 / num_peaks as f64)
                .max(1.0),
            frames_seen: 0,
            audio_duration_secs,
        }
    }

    /// `chunk` interleaved: the bin advances one frame at a time, not one
    /// sample, or multichannel audio would end up squeezed into the first bins.
    fn push(&mut self, chunk: &[f32], channels: usize) {
        let last = self.peaks.len() - 1;
        for frame in chunk.chunks_exact(channels.max(1)) {
            let bin = ((self.frames_seen as f64 / self.samples_per_bin) as usize).min(last);
            let peak = frame.iter().fold(0.0f32, |m, s| m.max(s.abs()));
            self.peaks[bin] = self.peaks[bin].max(peak);
            self.frames_seen += 1;
        }
    }

    /// Normalizes on the global peak: a quiet file still uses the full
    /// height of the clip.
    fn finish(mut self) -> Waveform {
        let global_peak = self.peaks.iter().copied().fold(0.0f32, f32::max);
        if global_peak > 0.0 {
            for p in &mut self.peaks {
                *p /= global_peak;
            }
        }
        Waveform {
            peaks: self.peaks,
            audio_duration_secs: self.audio_duration_secs,
        }
    }
}
/// Loads the already generated peaks for `content_hash`/`stream_index` from
/// the cache file, if it exists. `Ok(None)` if the file is missing (to be
/// generated) or corrupt.
pub fn load_waveform(content_hash: u64, stream_index: usize) -> Option<Waveform> {
    let path = waveform_path_for(content_hash, stream_index);
    let bytes = std::fs::read(&path).ok()?;
    read_peaks_file(&bytes)
}

/// Magic, version (u32), number of peaks (u32), audio duration (f64),
/// peaks (f32), all LE.
const PEAKS_MAGIC: &[u8; 4] = b"vbwf";
// v3: audio duration from the stream time_base.
// v4: bins of fractional samples (truncating them made the waveform slide).
const PEAKS_VERSION: u32 = 4;

fn write_peaks_file(path: &Path, peaks: &[f32], audio_duration_secs: f64) -> Result<(), crate::MediaError> {
    let mut bytes = Vec::with_capacity(20 + peaks.len() * 4);
    bytes.extend_from_slice(PEAKS_MAGIC);
    bytes.extend_from_slice(&PEAKS_VERSION.to_le_bytes());
    bytes.extend_from_slice(&(peaks.len() as u32).to_le_bytes());
    bytes.extend_from_slice(&audio_duration_secs.to_le_bytes());
    for p in peaks {
        bytes.extend_from_slice(&p.to_le_bytes());
    }
    Ok(std::fs::write(path, bytes)?)
}

fn read_peaks_file(bytes: &[u8]) -> Option<Waveform> {
    if bytes.len() < 20 || &bytes[..4] != PEAKS_MAGIC {
        return None;
    }
    let version = u32::from_le_bytes(bytes[4..8].try_into().ok()?);
    if version != PEAKS_VERSION {
        return None;
    }
    let count = u32::from_le_bytes(bytes[8..12].try_into().ok()?) as usize;
    let audio_duration_secs = f64::from_le_bytes(bytes[12..20].try_into().ok()?);
    if bytes.len() < 20 + count * 4 {
        return None;
    }
    let mut peaks = Vec::with_capacity(count);
    for chunk in bytes[20..20 + count * 4].as_chunks::<4>().0.iter() {
        peaks.push(f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
    }
    Some(Waveform {
        peaks,
        audio_duration_secs,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generates a real x264 file with AAC audio (a sine) via the ffmpeg CLI —
    /// the primary use case (compressed x264 + audio), not a mock.
    fn make_test_clip(file_name: &str, duration_secs: u32) -> PathBuf {
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join(file_name);
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                &format!("testsrc=size=320x240:rate=25:duration={duration_secs}"),
                "-f",
                "lavfi",
                "-i",
                &format!("sine=frequency=440:sample_rate=48000:duration={duration_secs}"),
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
                "-c:a",
                "aac",
            ],
            &path,
        );
        path
    }

    #[test]
    fn recommended_num_peaks_scales_with_duration_and_is_clamped() {
        assert_eq!(recommended_num_peaks(0.5), MIN_PEAKS);
        assert_eq!(recommended_num_peaks(60.0), 6000);
        assert_eq!(recommended_num_peaks(3600.0), MAX_PEAKS);
    }

    #[test]
    fn peaks_file_round_trips() {
        let peaks: Vec<f32> = (0..100).map(|i| (i as f32) / 99.0).collect();
        let bytes = {
            let mut b = Vec::new();
            b.extend_from_slice(PEAKS_MAGIC);
            b.extend_from_slice(&PEAKS_VERSION.to_le_bytes());
            b.extend_from_slice(&(peaks.len() as u32).to_le_bytes());
            b.extend_from_slice(&5.5f64.to_le_bytes());
            for p in &peaks {
                b.extend_from_slice(&p.to_le_bytes());
            }
            b
        };
        let loaded = read_peaks_file(&bytes).expect("read failed");
        assert_eq!(loaded.peaks, peaks);
        assert!((loaded.audio_duration_secs - 5.5).abs() < 1e-9);
    }

    #[test]
    fn peaks_file_rejects_bad_magic_and_version() {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(b"XXXX");
        bytes.extend_from_slice(&PEAKS_VERSION.to_le_bytes());
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&1.0f64.to_le_bytes());
        bytes.extend_from_slice(&0.5f32.to_le_bytes());
        assert!(read_peaks_file(&bytes).is_none());

        let mut bytes = Vec::new();
        bytes.extend_from_slice(PEAKS_MAGIC);
        bytes.extend_from_slice(&99u32.to_le_bytes()); // unknown version
        bytes.extend_from_slice(&1u32.to_le_bytes());
        bytes.extend_from_slice(&1.0f64.to_le_bytes());
        bytes.extend_from_slice(&0.5f32.to_le_bytes());
        assert!(read_peaks_file(&bytes).is_none());
    }

    #[test]
    fn generate_waveform_produces_normalized_peaks_and_caches_to_disk() {
        let path = make_test_clip("source.mp4", 2);
        let content_hash = 0xCAFEBABE;
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));

        assert!(!waveform_exists(content_hash, 0));
        let wf = generate_waveform(&path, content_hash, 0, 500)
            .expect("waveform generation failed")
            .expect("audio expected");
        assert_eq!(wf.peaks.len(), 500);
        assert!(waveform_exists(content_hash, 0));

        // A 440Hz sine is not silent: the global (normalized) peak must
        // reach 1.0 and the values must stay in [0,1].
        let peak = wf.peaks.iter().cloned().fold(0.0_f32, f32::max);
        assert!((peak - 1.0).abs() < 1e-6, "peak={peak}, expected 1.0 after normalization");
        assert!(wf.peaks.iter().all(|p| (0.0..=1.0).contains(p)));

        // The audio duration must be ~2s (the file is 2s long).
        assert!((wf.audio_duration_secs - 2.0).abs() < 0.2, "dur={:?}", wf.audio_duration_secs);

        // The cache file, read back, returns the same peaks.
        let reloaded = load_waveform(content_hash, 0).expect("reload failed");
        assert_eq!(reloaded.peaks, wf.peaks);
        assert!((reloaded.audio_duration_secs - wf.audio_duration_secs).abs() < 1e-9);
    }

    #[test]
    fn stereo_audio_peaks_are_not_compressed_into_the_first_half_of_bins() {
        // 4s stereo: silence in the first 2s, tone in the second 2s. With the
        // bug (global_sample advanced once per *interleaved sample* instead
        // of once per *frame*, hence twice as fast for stereo) the whole
        // waveform ended up squeezed/clamped into the first half of the bins,
        // and the tone (which starts at the middle of the real duration)
        // appeared already at 3/4 of the width instead of in the last
        // quarter — "the waveform runs ahead of the sound".
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("stereo_half_silent.mp4");
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                "aevalsrc=exprs='if(lt(t,2),0,sin(2*PI*440*t))':s=48000:d=4:c=stereo",
                "-c:a",
                "aac",
            ],
            &path,
        );

        let content_hash = 0x51DE7357;
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));
        let wf = generate_waveform(&path, content_hash, 0, 400)
            .expect("waveform generation failed")
            .expect("audio expected");

        // The tone starts exactly at the middle of the duration (2s of 4s): with
        // 400 bins, the bin where it comes out of the silence must be near bin
        // 200 (half the width). With the bug, the clamp at `num_peaks - 1` hid
        // a check too weak on "only the first/last portion" (the tone,
        // doubled in speed, still ended up crushed into the very last bin
        // rather than disappearing) — here we check the *position* of the
        // transition, not just that the tone shows up somewhere.
        let first_loud_bin = wf
            .peaks
            .iter()
            .position(|&p| p > 0.3)
            .expect("the tone should exceed the threshold somewhere");
        assert!(
            (170..230).contains(&first_loud_bin),
            "the tone starts at bin {first_loud_bin} (expected near bin 200, half of the 400 total bins for a transition halfway through the 4s)"
        );
    }

    /// The same silence->tone transition as the stereo test, but on 6 channels
    /// (5.1 side, the exact layout of the real file that exposed the stereo
    /// channel bug — bbb_sunflower with a 5.1 AC-3 track): checks that the
    /// `chunks_exact(channels)` fix holds for channels > 2 too, not just
    /// the 2-channel case already covered.
    /// With a non-integer number of samples per bin (the normal case: the
    /// bins come from the video duration) the position of the peaks must
    /// not slide along the file.
    #[test]
    fn peaks_stay_aligned_when_samples_per_bin_is_fractional() {
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("tone_at_8s.wav");
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                "aevalsrc=exprs='if(lt(t,8),0,sin(2*PI*440*t))':s=48000:d=10",
            ],
            &path,
        );

        let content_hash = 0xF4AC7;
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));
        // 480000 samples / 250000 bins = 1.92 samples per bin.
        let num_peaks = 250_000;
        let wf = generate_waveform(&path, content_hash, 0, num_peaks)
            .expect("waveform generation failed")
            .expect("audio expected");
        let first_loud_bin = wf.peaks.iter().position(|&p| p > 0.3).expect("tone expected");
        let expected = num_peaks * 8 / 10;
        assert!(
            // The sine starts at 0: it crosses the threshold a few samples later.
            first_loud_bin.abs_diff(expected) <= 5,
            "tone at bin {first_loud_bin}, expected {expected} (8 s out of 10)"
        );
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));
    }

    #[test]
    fn six_channel_audio_peaks_are_not_compressed_into_the_first_half_of_bins() {
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("six_channel_half_silent.mp4");
        let tone = "if(lt(t,2),0,sin(2*PI*440*t))";
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                &format!("aevalsrc=exprs='{tone}|{tone}|{tone}|{tone}|{tone}|{tone}':s=48000:d=4:c=5.1"),
                "-c:a",
                "ac3",
            ],
            &path,
        );

        let content_hash = 0x51DE7357_6C6C6C6C;
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));
        let wf = generate_waveform(&path, content_hash, 0, 400)
            .expect("waveform generation failed")
            .expect("audio expected");

        let first_loud_bin = wf
            .peaks
            .iter()
            .position(|&p| p > 0.3)
            .expect("the tone should exceed the threshold somewhere");
        assert!(
            (170..230).contains(&first_loud_bin),
            "the tone starts at bin {first_loud_bin} (expected near bin 200, half of the 400 total bins for a transition halfway through the 4s)"
        );
    }

    #[test]
    fn generate_waveform_returns_none_for_a_video_without_audio() {
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("silent.mp4");
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                "testsrc=size=320x240:rate=25:duration=1",
                "-c:v",
                "libx264",
                "-pix_fmt",
                "yuv420p",
            ],
            &path,
        );

        let result = generate_waveform(&path, 0xDEADBEEF, 0, 200).expect("generation failed");
        assert!(result.is_none(), "no audio track: no peaks");
    }

    /// A file with two audio streams (see `audio::decode_audio_track_selects_the_requested_stream_index_not_just_the_best`
    /// for the same fixture): the waveform generated for stream 1 must be
    /// the one of the *second* signal, not always fall back to the first.
    #[test]
    fn generate_waveform_selects_the_requested_stream_index() {
        let dir = std::env::temp_dir().join("vv-media-waveform-test");
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("two_streams.mp4");
        crate::test_support::ffmpeg(
            &[
                "-f",
                "lavfi",
                "-i",
                "sine=frequency=440:sample_rate=44100:duration=1",
                "-f",
                "lavfi",
                "-i",
                "sine=frequency=880:sample_rate=48000:duration=1",
                "-map",
                "0:a",
                "-map",
                "1:a",
                "-c:a",
                "aac",
            ],
            &path,
        );

        let content_hash = 0x57EA2001;
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 0));
        let _ = std::fs::remove_file(waveform_path_for(content_hash, 1));

        let first = generate_waveform(&path, content_hash, 0, 200)
            .unwrap()
            .expect("stream 0 expected");
        assert!((first.audio_duration_secs - 1.0).abs() < 0.2);

        let second = generate_waveform(&path, content_hash, 1, 200)
            .unwrap()
            .expect("stream 1 expected");
        assert!((second.audio_duration_secs - 1.0).abs() < 0.2);

        assert!(
            generate_waveform(&path, content_hash, 2, 200).unwrap().is_none(),
            "no audio stream at index 2"
        );
    }
}